title: "ShayaanQ.github.io"
name: "Shayaan Qureshi"
description: "Computer Science student at the University of Houston (Expected Fall 2026)"
url: ""
baseurl: ""

google_analytics: G-0H159VRHVQ

minimal_mistakes_skin: "dark"

defaults:
  - scope:
      path: ""
    values:
      author_profile: false

custom_css:
  - /assets/css/custom.css

footer:
  links: []

copyright: "Â© 2026 Shayaan Qureshi"
